USE ROLE ML_MODEL_HOL_USER;
USE DATABASE ML_HOL_DB;

DROP WAREHOUSE IF EXISTS ML_HOL_WH;
DROP STAGE IF EXISTS DIAMONDS_ASSETS;
DROP STAGE IF EXISTS ML_HOL_ASSETS;
DROP EXTERNAL ACCESS INTEGRATION IF EXISTS allow_all_integration;
DROP NETWORK RULE IF EXISTS allow_all_rule;
DROP API INTEGRATION IF EXISTS GITHUB_INTEGRATION_ML_HOL;
DROP DATABASE IF EXISTS ML_HOL_DB;
